name: "ludum-dare-38-bin"
command-type: EXECUTABLE
persist: true

commands:

  node:
    image: "node:7.9.0-alpine"

  yarn:
    image: "node:7.9.0-alpine"
    container-command: "yarn"

  inode:
    image: "node:7.9.0-alpine"
    container-command: "/bin/sh"

  webpack:
    image: "jmfirth/webpack:7"