#!/usr/bin/env bash
echo "building...."

rm -rf ./docs/*
. .env
webpack

if [ $? -ne 0 ]; then
        echo "build blew up!"
        # osascript -e "display alert \"Build Error\" message \"Something bad :( \""
else
        echo "finished."
        # osascript -e "display notification \"Build finished\" with title \"webpack builder\""
fi

